//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExamDBEntities1 : DbContext
    {
        private static ExamDBEntities1 _context;

        public static ExamDBEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new ExamDBEntities1();
            }

            return _context;
        }

        public ExamDBEntities1()
            : base("name=ExamDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<places> places { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
